import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import { products } from '../src/data/products.js';

// Setup __dirname for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env from root
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Error: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set in .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function seedProducts() {
  console.log('Seeding products to Supabase...');
  
  // Format products for Supabase (removing id if we want auto-increment, 
  // but since the original had ids, we can keep them or let Supabase handle it)
  // Our schema uses BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, so we can keep the ids.
  
  const formattedProducts = products.map(p => ({
    id: p.id,
    name: p.name,
    category: p.category,
    price: p.price,
    description: p.description,
    image: p.image
  }));

  const { data, error } = await supabase
    .from('products')
    .upsert(formattedProducts, { onConflict: 'id' });

  if (error) {
    console.error('Error seeding products:', error.message);
  } else {
    console.log('Successfully seeded products!');
  }
}

seedProducts();
